### ISSUE TITLE
Installation sadly broken

### ISSUE THREAD

**Issue by fluffymadness** [Miosame/flatline#18]
I'd love to use this project.
I tried to install it in an alpine linux vm via docker compose.
Sadly the flatline_php container seems broken. I get a vendor/autoload.php error.
The solution to fixing this would be to manually install composer
https://getcomposer.org/download/
and then doing a composer install in the /usr/share/nginx/html directory.
However when doing this I get another error message....
Do you maybe have a solution for this?

**Comment by Miosame** [comment]
@fluffymadness thanks for the heads up, didn't ever find the time to check if dependabot broke anything (especially because it bumped laravel), https://github.com/Miosame/flatline/commit/8181f16941fedd8e002c0397d8e6af0136e6b27d should fix this, try again and note, you don't docker-compose yourself, use `installer.sh` provided.

Cheers! :tada:

**Comment by fluffymadness** [comment]
Thank you, it works now. Another question, is it just something with my network/configuration or is hostname discovery not yet implemented?
All hosts initially have "-" as hostname, I know I can name each one, but i have a lot of iot-nodes ^^.
If I have to name each one, is the mapping tied to the mac address in the database ? Meaning does the hostname stay when the ip changes?

**Comment by Miosame** [comment]
> is it just something with my network/configuration or is hostname discovery not yet implemented?

not all devices report back their hostname, hence they will be marked as `-`.

> is the mapping tied to the mac address

yes.

**Comment by fluffymadness** [comment]
I have 17 devices atm in the vlan I'm scanning right now. None of them is showing a hostname atm. Even the windows pc just shows -.

**Comment by fluffymadness** [comment]
Anyway, my initial bug is solved :)
So, closing this now.

**Comment by Miosame** [comment]
Looking at fing, they seem to use DNS lookups, which nmap supports too, I'll add it as a feature and quickly look over it if it's feasible to implement.
