### ISSUE TITLE
Add DNS resolution for hostnames

### ISSUE THREAD

**Issue by Miosame** [Miosame/flatline#19]
Currently most hostname lookups fail, however forcing a dns lookup in e.g. nmap
`nmap -R --dns-servers 192.168.0.1 192.168.0.24`
seems to yield good results.

This would require a new .env value to enter the correct router IP (provided it does local dns), as automatically guessing it would most likely fail most of the time anyway.

**Comment by Miosame** [comment]
@fluffymadness

Try out the following branch, locally it now resolves for me every single device because my router supports local-dns https://github.com/Miosame/flatline/tree/feature-hostnames-local-dns

note running `install.sh` again, will wipe your previous database, so if you want to keep it, try it in e.g. another folder instead of cloning into the same one.

**Comment by fluffymadness** [comment]
I just tested it, works good. Do you think you could add custom table sorting ?
Right now it is sorted via hostname. Ip address ascending sorting, or sorting via online/offline status would be extremely useful i think.
Maybe something like this, where it is just needed to click on the table headers to change sorting orders.
https://mdbootstrap.com/docs/b4/jquery/tables/sort/

**Comment by Miosame** [comment]
@fluffymadness awesome, merged it in, closing this issue out and opened https://github.com/Miosame/flatline/issues/20 with your suggestion, not sure when I'll get to it though, because I want to keep the design aspects and putting something like datatables in, would mean I'd have to hackily retheme it all to fit the original look.
