### ISSUE TITLE
SCAN_DNS_SERVER =  says invalid ip - clarify

### ISSUE THREAD

**Issue by lazee486** [Miosame/flatline#22]
SCAN_DNS_SERVER = 
Set to 10.0.5.2 (local pihole server with unbound) in the .env file, goes fine until scrapers first run when it stops the container with

`node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_IP_ADDRESS]: Invalid IP address: "10.0.5.2"
    at new NodeError (node:internal/errors:371:5)
    at node:internal/dns/utils:117:13
    at Array.forEach (<anonymous>)
    at Resolver.setServers (node:internal/dns/utils:82:5)
    at Object.defaultResolverSetServers [as setServers] (node:dns:280:12)
    at /usr/src/app/scraper.js:43:11
    at async Promise.all (index 33)
    at async /usr/src/app/scraper.js:34:3 {
  code: 'ERR_INVALID_IP_ADDRESS'
}`
 in portainer....

the readme doesnt really describe (for less technical people like me) what this field is for...
what issue does it have with that ip address?

homelab is 10.0.5.0/24 range
going to run a second instance to watch my vpn range and see which devices online there too...

**Comment by Miosame** [comment]
Try wrapping it in quotes, note this was a recent addition and you can simply leave it empty, it's there for DNS that support local name resolving. (usually routers, unbound/pihole etc need to be specifically setup to passthrough it from the router or smth)

**Comment by Miosame** [comment]
Oh actually it might be **because** of the quotes, try removing them, if that's the fix I know what's wrong.

**Comment by lazee486** [comment]
sorry, that was in quotes, "10.0.5.2" failed, so did "",  i eventually removed whole line and that worked,(error during install saying using default....) but its up and looking amazing :)  thx for the nice project :)

**Comment by lazee486** [comment]
reloaded it to test for you, no quotation marks works...
then it populates dns names nicely from pihole :)

**Comment by Miosame** [comment]
awesome, fixed in https://github.com/Miosame/flatline/commit/406a68edcf78ea37815382280db2fe8a2e786c1d :tada:
